### ISSUE TITLE
Why Mazak CNC machine Power_State value unavailable ?

### ISSUE THREAD

**Issue by Ruei1996** [ctacke/mtconnect#2]
![ask](https://user-images.githubusercontent.com/36985205/43112721-01ae6c22-8f2a-11e8-9e9c-7ac4e6b96ae8.png)

Hi,author  I'm using [this](https://archive.codeplex.com/?p=mtconnect) 

I am developing a windows client application based on this open source project.

But there are always a few nodes whose value are "unavailable"

BTW, the MTconnect version of the machine is 1.3

**Comment by ctacke** [comment]
It's due the the MTConnect Adapter on the machine itself returning that value.  You can verify that in a browser by navigating to http://192.168.21.117:5000/current and you'll find a Data Item with an id of "pwr" and a value of "UNAVAILABLE"

**Comment by Ruei1996** [comment]
@ctacke  Thank you very much!!
